### ISSUE TITLE
这东西怎么用啊

### ISSUE THREAD

**Issue by Dovuq** [Ikaros-521/html_login_register#1]
QwQ

**Comment by Ikaros-521** [comment]
你得搭好boa服务，然后才能跑页面




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dovuq"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月16日(星期一) 晚上11:15
收件人:&nbsp;"Ikaros-521/html_login_register"<html_login_register@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Ikaros-521/html_login_register] 这东西怎么用啊 (#1)





 
rt

**Comment by Ikaros-521** [comment]
操作系统：Ubuntu12.04 LTS
boa下载地址（网址突然复活了）：http://www.boa.org/
我是其他网站找到的资源，但是忘了网址了，所以我直接上云盘资源
链接:&nbsp;https://pan.baidu.com/s/1_SpR9MDcmSB8jpDm76fw6A&nbsp;提取码: hb1e
可以参考：Ubuntu下boa服务器的配置与搭建
嵌入式linux项目开发（一）——BOA移植
cgi：直接终端安装 sudo apt-get install apache2
可以参考：&nbsp;ubuntu 下搭建cgi环境




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dovuq"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月16日(星期一) 晚上11:15
收件人:&nbsp;"Ikaros-521/html_login_register"<html_login_register@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Ikaros-521/html_login_register] 这东西怎么用啊 (#1)





 
rt

**Comment by Dovuq** [comment]
谢奆佬

**Comment by Ikaros-521** [comment]
这个是我已经配好的boa，端口是886，把web项目抛到/var/www下面，cgi程序编译好放在/var/www/cgi-bin，浏览器访问ip:886/index.html简单测一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dovuq"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月17日(星期二) 上午10:31
收件人:&nbsp;"Ikaros-521/html_login_register"<html_login_register@noreply.github.com&gt;;
抄送:&nbsp;"Love丶伊卡洛斯"<327209194@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Ikaros-521/html_login_register] 这东西怎么用啊 (#1)





 
谢奆佬

**Comment by Ikaros-521** [comment]
==，我搞错了。你要跑这个登录页面的话，直接运行&nbsp;index.html 就可以了。或是装个phpstudy




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dovuq"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月17日(星期二) 上午10:31
收件人:&nbsp;"Ikaros-521/html_login_register"<html_login_register@noreply.github.com&gt;;
抄送:&nbsp;"Love丶伊卡洛斯"<327209194@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Ikaros-521/html_login_register] 这东西怎么用啊 (#1)





 
谢奆佬

**Comment by Ikaros-521** [comment]
> QwQ

我搞错了，这个直接运行就可以了

**Comment by Ikaros-521** [comment]
> QwQ

我还以为是另一个项目，这个直接运行就可以用，或者装个phpstudy，抛到上面运行

**Comment by Ikaros-521** [comment]
> QwQ

github被墙了，刚搭了个代理才上来看看情况

**Comment by Dovuq** [comment]
Thx

**Comment by Ikaros-521** [comment]
> Thx

可以直接运行的，你可以试试
